### PR TITLE
Upgrade to postgres Dockerfile to install 9.6.3

### PR DESCRIPTION
**Pull request by urbanslug**
Update postgres with postgis Dockerfile
Add a docker-compose.yml

### CODE REVIEW

**Review by ukanga — COMMENTED** [review]
Why are the permissions very open?

**Comment by urbanslug** [comment]
@ukanga Which permissions would you prefer? 

I assumed this would only be done in dev env.

**Comment by urbanslug** [comment]
@ukanga It's really just an edit of https://github.com/docker-library/postgres/blob/54053ad27ac099abff3d4964bf7460fb9c541d5d/9.6/Dockerfile

**Comment by ukanga** [comment]
I think I freak out whenever someone sets global access permissions on things that are best "secure" if they are accessible by the user that writes and makes use of the records. I also missed the part where it says it gets converted to 700 at runtime. I was trying to figure out why it was necessary for the permission to be set to 777.

**Pull request merged**
